# coding=utf-8
"""Shared workflow contracts and options."""

from newspulse.workflow.shared.ai_runtime import (
    AIConfigError,
    AIInvocationError,
    AIPromptError,
    AIResponseDecodeError,
    AIRuntimeClient,
    AIRuntimeConfig,
    AIRuntimeError,
    EmbeddingRuntimeClient,
    EmbeddingRuntimeConfig,
    PromptTemplate,
    PromptTemplateNotFoundError,
    coerce_text_content,
    decode_json_response,
    extract_json_block,
    load_prompt_template,
)
from newspulse.workflow.shared.contracts import (
    DeliveryPayload,
    HotlistItem,
    HotlistSnapshot,
    InsightResult,
    InsightSection,
    ReportContent,
    ReportIntegrity,
    ReportPackage,
    ReportPackageMeta,
    SelectionGroup,
    SelectionRejectedItem,
    SelectionResult,
    SourceFailure,
    StandaloneSection,
)
from newspulse.workflow.shared.options import (
    DeliveryOptions,
    InsightOptions,
    RenderOptions,
    SelectionAIOptions,
    SelectionOptions,
    SelectionSemanticOptions,
    SnapshotOptions,
    WorkflowOptions,
)

__all__ = [
    "AIConfigError",
    "AIInvocationError",
    "AIPromptError",
    "AIResponseDecodeError",
    "AIRuntimeClient",
    "AIRuntimeConfig",
    "AIRuntimeError",
    "EmbeddingRuntimeClient",
    "EmbeddingRuntimeConfig",
    "DeliveryOptions",
    "DeliveryPayload",
    "HotlistItem",
    "HotlistSnapshot",
    "InsightOptions",
    "InsightResult",
    "InsightSection",
    "PromptTemplate",
    "PromptTemplateNotFoundError",
    "ReportContent",
    "ReportIntegrity",
    "ReportPackage",
    "ReportPackageMeta",
    "RenderOptions",
    "SelectionAIOptions",
    "SelectionGroup",
    "SelectionRejectedItem",
    "SelectionOptions",
    "SelectionResult",
    "SelectionSemanticOptions",
    "SnapshotOptions",
    "SourceFailure",
    "StandaloneSection",
    "WorkflowOptions",
    "coerce_text_content",
    "decode_json_response",
    "extract_json_block",
    "load_prompt_template",
]
