# coding=utf-8
"""Shared workflow contracts and options."""

from newspulse.workflow.shared.ai_runtime import (
    AIConfigError,
    AIInvocationError,
    AIPromptError,
    AIResponseDecodeError,
    AIRuntimeClient,
    AIRuntimeConfig,
    AIRuntimeError,
    PromptTemplate,
    PromptTemplateNotFoundError,
    coerce_text_content,
    decode_json_response,
    extract_json_block,
    load_prompt_template,
)
from newspulse.workflow.shared.contracts import (
    DeliveryPayload,
    HotlistItem,
    HotlistSnapshot,
    InsightResult,
    InsightSection,
    LocalizedReport,
    RenderableReport,
    SelectionGroup,
    SelectionResult,
    SourceFailure,
    StandaloneSection,
)
from newspulse.workflow.shared.options import (
    DeliveryOptions,
    InsightOptions,
    LocalizationOptions,
    LocalizationScope,
    RenderOptions,
    SelectionAIOptions,
    SelectionOptions,
    SnapshotOptions,
    WorkflowOptions,
)

__all__ = [
    "AIConfigError",
    "AIInvocationError",
    "AIPromptError",
    "AIResponseDecodeError",
    "AIRuntimeClient",
    "AIRuntimeConfig",
    "AIRuntimeError",
    "DeliveryOptions",
    "DeliveryPayload",
    "HotlistItem",
    "HotlistSnapshot",
    "InsightOptions",
    "InsightResult",
    "InsightSection",
    "LocalizationOptions",
    "LocalizationScope",
    "LocalizedReport",
    "PromptTemplate",
    "PromptTemplateNotFoundError",
    "RenderOptions",
    "RenderableReport",
    "SelectionAIOptions",
    "SelectionGroup",
    "SelectionOptions",
    "SelectionResult",
    "SnapshotOptions",
    "SourceFailure",
    "StandaloneSection",
    "WorkflowOptions",
    "coerce_text_content",
    "decode_json_response",
    "extract_json_block",
    "load_prompt_template",
]
